# Generated by Django 4.2.3 on 2023-08-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                error_messages={
                    "content": ["Este campo não pode estar vazio."]
                }
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                error_messages={"imae": ["Este campo não pode estar vazio."]},
                upload_to="",
            ),
        ),
    ]
