# Generated by Django 4.2.3 on 2023-08-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_content_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                error_messages={"blank": "Este campo não pode estar vazio."}
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
