# Generated by Django 4.2.3 on 2023-08-22 20:02

from django.db import migrations, models
import news.models.news_model


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0010_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                error_messages={"blank": ["Este campo não pode estar vazio."]},
                max_length=200,
                validators=[news.models.news_model.News.validate_word_count],
            ),
        ),
    ]
