from news_rest.serializers.categories_serializer import CategoriesSerializer
from news_rest.serializers.user_serializer import UsersSerializer
from news_rest.serializers.news_serializer import NewsSerializer